#!/bin/bash

# Created by Charl van Niekerk <charlvn@charlvn.com> & Derek Keats <derek@deats.com>
#
# Copyleft 2010 AVOIR & Kenga -  GPL
#
# This BASH script prepares a developer copy of Chisimba on a fresh install of Ubuntu

clear
echo "Working .... "
sudo apt-get install subversion apache2 mysql-server mysql-client php5 php5-mysql php5-imap php5-gd php5-curl php-pear php5-imagick php5-imap php5-ldap php5-mapscript php5-mcrypt php5-memcache php5-mysql php5-pgsql php5-pspell php5-snmp php5-sqlite php5-tidy php5-uuid php5-xmlrpc php5-xsl

echo "Server backend software installed."
echo "Installing and setting up PEAR..."

sudo pear channel-update pear.php.net
sudo pear upgrade pear
sudo pear upgrade-all
sudo pear install --alldeps -f Config Log
sudo pear install MDB2-2.5.0b2 
sudo pear install  --alldeps -f  MDB2_Driver_mysql
sudo pear install  --alldeps -f  MDB2_Driver_pgsql
sudo pear install  --alldeps -f  MDB2_Driver_mysqli
sudo pear install  --alldeps -f MDB2_Schema 

echo "PEAR installed and updated."

sudo chown -R $USER:$USER /var/www
rm /var/www/index.html

echo "Changed ownership to www-data:www-data on /var/www"
echo "Removed /var/www/index.html"
echo "Creating Chisimba development directory in your home directrory."
cd ~
mkdir chisimba
cd chisimba

echo "Checking out chisimba from git and subversion"

git clone git://github.com/chisimba/chisimba.git framework
# If you have commit rights on github Chisimba, and you have correctly
# set up your SSH keys, comment out the above line, and uncomment the
# line below.
#git clone git@github.com:chisimba/chisimba.git framework
svn co https://cvs2.uwc.ac.za/chisimba/modules/trunk/ modules
svn co https://cvs2.uwc.ac.za/chisimba/canvases canvases

# If you want any of the other components, uncomment the 
# appropriate line below
#svn co https://cvs2.uwc.ac.za/chisimba/skins/trunk/ skins
#svn co https://cvs2.uwc.ac.za/chisimba_documentation/ docs
#svn co https://cvs2.uwc.ac.za/chisimba/branding/ branding
#svn co https://cvs2.uwc.ac.za/chisimba/interop/ interop
#svn co https://cvs2.uwc.ac.za/chisimba/shellscripts/ shellscripts

echo "Checkout complete."
echo "NOTE: Your first site will be in /var/www/ch"
echo "      You can access this as http://localhost/ch after install is completed"
echo "Doing permissions and symlinks..."

chmod -R ga+rw framework/
chmod -R ga+rw modules/
chmod -R ga+rw canvases/

cd /var/www
mkdir ch
cd ch
ln -s /home/$USER/chisimba/framework/app/index.php .
ln -s /home/$USER/chisimba/framework/app/gateway.php .
ln -s /home/$USER/chisimba/framework/app/classes/ .
ln -s /home/$USER/chisimba/framework/app/core_modules/ .
ln -s /home/$USER/chisimba/framework/app/cron/ .
ln -s /home/$USER/chisimba/framework/app/installer/ .
ln -s /home/$USER/chisimba/framework/app/lib/ .

#Create a directory for skins and link it in
mkdir skins
cd skins
ln -s /home/$USER/chisimba/framework/app/skins/* .
cd ..

#Create a directory for user_images and link it in
mkdir user_images
cd user_images/
ln -s /home/$USER/chisimba/framework/app/user_images/* .
cd ..

#Link the modules into the packages directory which Chisimba expects
ln -s /home/$USER/chisimba/modules/ packages

#Make it very insecure - only for a developer machine
chmod 777 -R /var/www/ch
#chmod -R ga+rw /var/www/ch

#restart apache (uncomment the one that works for you and comment out the other)
#sudo /etc/init.d/apache2 restart
sudo service apache2 reload

firefox http://localhost/ch/
